version: '3.9'

services:
  bot:
    build: .
    container_name: rovmarket-bot
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    command: python rovmarket_bot/main.py

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight Web UI (по желанию)
    volumes:
      - redis-data:/data

    restart: unless-stopped

  postgres:
    image: postgres:15  # фиксированная версия — лучше для стабильности
    container_name: postgres
    environment:
      POSTGRES_USER: danil
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: danil_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:
