"""add notifications_all_ads

Revision ID: 236c700f31b4
Revises: b612f0f69bb9
Create Date: 2025-08-10 22:10:05.511590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236c700f31b4'
down_revision: Union[str, Sequence[str], None] = 'b612f0f69bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notifications_all_ads', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notifications_all_ads')
    # ### end Alembic commands ###
