"""product, categories

Revision ID: 7aad7a0d96d2
Revises: c1f6ee1a2cbf
Create Date: 2025-08-03 00:38:47.825929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aad7a0d96d2'
down_revision: Union[str, Sequence[str], None] = 'c1f6ee1a2cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
