"""add settings notifications_all

Revision ID: a5aa6ceefa1e
Revises: e76795241808
Create Date: 2025-08-11 11:31:46.395975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5aa6ceefa1e'
down_revision: Union[str, Sequence[str], None] = 'e76795241808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_settings', sa.Column('notifications_all', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_settings', 'notifications_all')
    # ### end Alembic commands ###
